---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Hosted Services:
  - Media server:
      icon: mdi-television
      href: https://media.27hs.co.uk
      description: Enjoy a selection of films, TV shows, books, music and videos from the YouTube archive. 

  - YouTube archive:
      icon: mdi-youtube-tv
      href: https://youtube.27hs.co.uk
      description: Browse and schedule downloads in the YouTube archiver

  - Photos and videos:
      icon: mdi-camera
      href: https://pics.27hs.co.uk
      description: Access your personal collection of photos & videos

  - Torrents:
      icon: mdi-skull-crossbones-outline
      href: https://bt.27hs.co.uk
      description: Aaaargh!

  - Documents:
      icon: mdi-invoice-list
      href: https://docs.27hs.co.uk
      description: Access your personal letters, invoices, forms, etc.

  - Goblin:
      icon: mdi-cloud
      href: https://admin.27hs.co.uk
      description: Manage the containers hosted on Goblin

  - Nexus:
      icon: mdi-creation
      href: https://nexus.27hs.co.uk
      description: Enter the Nexus to perform administrative tasks

  - CCTV:
      icon: mdi-cctv
      href: https://cctv.27hs.co.uk
      description: Real-time monitoring and management of all CCTV cameras and recordings

