---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

#- resources:
#    cpu: true
#    memory: true
#    disk: /

#53.1051Â°N 0.1752Â°W

- greeting:
    text_size: x1
    text: don't forget to feed the cat ğŸ­

- search:
    provider: google
    target: _blank

- openweathermap:
    label: Coningsby
    latitude: 53.1051
    longitude: 0.1752
    units: metric 
    provider: openweathermap
    cache: 5 
    format: 
      maximumFractionDigits: 1


